---
language: java
sudo: true 
git:
install: true
script:
    - bash ./travis-build.sh
jdk:
    - openjdk7
cache:
  directories:
  - $HOME/.m2
notifications:
  email:
  - jason.p.pickering@gmail.com
env:
    global:
    - TERM=dumb
